- id: jsonschema-validate
  name: Validate JSON against JSON Schema
  description: ensure json files follow specified JSON Schema
  entry: jv
  language: golang
  additional_dependencies:
  - ./cmd/jv

- id: govendor
  name: govendor
  description: ensure cmd/jv/govendor.toml is in sync with cmd/jv/go.mod
  entry: govendor --check ./cmd/jv
  language: golang
  files: (^|/)go\.mod$
  pass_filenames: false
